### ISSUE TITLE
Login not showing environments

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#103]
Hi John,
'
I am unable to proceed past the welcome screen, and my environments are not showing up. It does appear I am logged in correctly.

**Comment by jakemannion** [comment]
It is now working as expected

**Comment by johnnliu** [comment]
I've seen a few hiccups like that recently - next time if you see this, take a screenshot for me - is it blank with only the top header showing?

and possibly hit F12 and see if there are any errors reported in the debug console.

**Comment by jakemannion** [comment]
Oh, good idea, yes - I will definitely remember to do that if something like this happens again.

**Comment by johnnliu** [comment]
tracking (in my head)  but nothing to do for this one right now.
