### ISSUE TITLE
Navigation stuck on /token and doesn't go anywhere

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#123]
Stuck on https://flow-studio.azurewebsites.net/token

﻿console log:

main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info State status:true; Request type:LOGIN
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info State is right
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info Fragment has id token
main.4a92b31….js:1 login success {"_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6InU0T2ZORlBId0VCb3NIanRyYXVPYlY4NExuWSJ9.eyJhdWQiOiI5MTcyM2E1Zi1lZjI4LTQzOTMtYWE0Zi03YmJjMzM3OWYxMzEiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vOWVmZDU2ZGQtZTlkYi00M2JmLTg0NDctNjBkNDQxM2I1OTRhL3YyLjAiLCJpYXQiOjE1NjI4NjYyNjYsIm5iZiI6MTU2Mjg2NjI2NiwiZXhwIjoxNTYyODcwMTY2LCJhaW8iOiJBVFFBeS84TUFBQUFTcEJjcEJScnQyekNwWFJnbCt1V1ZzZVlNK29HZExDV2JNVms5MkpicHZIb1JwRzdQVU1LZFRlbXdIWk1jNFM1IiwibmFtZSI6Ikpha2UgTWFubmlvbiIsIm5vbmNlIjoiNzgyZjg0MzctYjJmMC00OWVlLThkN2YtMGE4MmMwZjFlNjY5Iiwib2lkIjoiMzUzYWQwODItMzgwZi00NjMzLWI5OWMtNjhmMmMwMmM0MDNiIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiamFrZS5tYW5uaW9uQHN0YW5kYXJkLmNvbSIsInN1YiI6InhqY21OcVV5QU9GRmlJeFkxTmhiZGtGUUk2MWRXUldDanN2RzVFaHVKZUkiLCJ0aWQiOiI5ZWZkNTZkZC1lOWRiLTQzYmYtODQ0Ny02MGQ0NDEzYjU5NGEiLCJ1dGkiOiJrX2ZkUXBJeXcwU3dMeHVuV3NPQkFBIiwidmVyIjoiMi4wIn0.MNLrXEGbXZOiOIFa-Y3tGYPaPGvGWhs-x6NmoWgUg_Peo_zRHVrtppW6meG6uRn-_zh3as3vvfM5x1gtUS9dPIouQILJ3Rn9bTVPejc5jQti6p6dRr_DD3rjQ1Xf8yIfv64b2NOzPsPRZACAAQNY__B7ogaADuKfi5nK0ZeFS9vY2xApkgxPVHcLcLRzxTXw-QAwSzCWgqbqpZ_Azl6YcAx-wLFf7KyxmIn9iv_jV5SnPvSs77AJuu7c4Q_CqCiphGB6jO3Khb1t23vxi79qD1uW61rJkepSBoP9GoUUfwU8RcrlOwZ3eLNf8yGmJJwbNI-iAhlZlEElBbg_KIlqcQ","_tokenType":"id_token"}
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info Add msal frame to document:msalRenewFramehttps://management.azure.com/user_impersonation
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info Navigate to:https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_typ…a&login_req=353ad082-380f-4633-b99c-68f2c02c403b&domain_hint=organizations
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:10 GMT:1000-0.2.1-Info LoadFrame: msalRenewFramehttps://management.azure.com/user_impersonation
main.4a92b31….js:1 lastroute: /deploy
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:11 GMT:1000-0.2.1-Info Add msal frame to document:msalRenewFramehttps://management.azure.com/user_impersonation
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:11 GMT:1000-0.2.1-Info Frame Name : msalRenewFramehttps://management.azure.com/user_impersonation Navigated to: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_typ…a&login_req=353ad082-380f-4633-b99c-68f2c02c403b&domain_hint=organizations
main.4a92b31….js:1 Bootstrap: MSAL
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:12 GMT:1000-0.2.1-Info State status:true; Request type:RENEW_TOKEN
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:12 GMT:1000-0.2.1-Info State is right
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:12 GMT:1000-0.2.1-Info Fragment has access token
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:12 GMT:1000-0.2.1-Info The user object received in the response is the same as the one passed in the acquireToken request
main.4a92b31….js:1 client loggingThu, 11 Jul 2019 17:36:13 GMT:1000-0.2.1-Info Token is already in cache for scope:https://management.azure.com/user_impersonation

**Comment by jakemannion** [comment]
this one is not a big deal. refresh resolved it. but wanted to log the issue, in case it proved helpful
