### ISSUE TITLE
Feedback for FlowStudio from Shaun****

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#164]
I'm confused, a trail means I am supposed to be able to edit my JSON.  Right?  I can edit it, but I cannot save it?

Am I missing something?

shaun@arrowconsultants.solutions

Please advise.

Thank you!
Shaun

**Comment by nagero80** [comment]
I'm in the same boat and have a Pro licence - there is no trace of the save button in the menu

**Comment by johnnliu** [comment]
:-O wait let me check.

**Comment by johnnliu** [comment]
fixed 1.0.10
