### ISSUE TITLE
Edit JSON save button

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#165]
Hello!

So you're going to have to forgive me if I'm being really stupid here, but where has the save button gone from the edit json screen? I've tried across multiple browsers, Mac and PC, and there doesn't appear to be any errors (or reference to the button!) on the kendo-toolbar. 

Here's a screenshot:  https://1drv.ms/u/s!Av0RmDCwaEz3sz5z5-YGPcKoMHer?e=CQz4bg

Thanks! 

Mike

**Comment by johnnliu** [comment]
Sorry fixed.

**Comment by nagero80** [comment]
Thank god it wasn't me!  thanks man.
