### ISSUE TITLE
Feedback for FlowStudio from rgreen****

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#285]
I need multi-seat billing using invoice through our company and need it soon.  I have emailed support my email is RyanGreen@playlsi.com.  Can someone get back to me today?

**Comment by rgreenPlayLSI** [comment]
Hi @johnnliu We have paid the subscription for Pro but still are not able to access via our accounts can you take a look?

![image](https://github.com/johnnliu/Flow-Studio-Issues/assets/110482679/b2d88eaa-c70f-42f4-835e-a8774d95c458)

**Comment by rgreenPlayLSI** [comment]
@johnnliu  any update? We have purchased and as I see it can not use until our IDs are associated.

**Comment by johnnliu** [comment]
hello sorry, I fixed and responded this via support this morning.
