### ISSUE TITLE
Flow run Succeeded / Failed icons

### ISSUE THREAD

**Issue by zplume** [johnnliu/Flow-Studio-Issues#39]
As with the https://[region].flow.microsoft.com/manage/environments/[id]/flows/[id]/details page, a green tick icon next to successful Flow runs or a red alert icon next to Failed Flow runs would make it quicker to scan recent activity for a particular Flow.

In terms of accessibility, you could go one better than Flow using something like https://michelf.ca/projects/mac/sim-daltonism to get an idea of how contrast between success/failure icons looks for people with various forms of colour-blindness. Flow's success/failure icons look very similar at a glance with the Red-Green Sim Daltonism app filters applied.

This article gives a good overview on designing for colour blindness:
http://blog.usabilla.com/how-to-design-for-color-blindness

One suggestion from the above is using both colour and texture to provide contrast. Or perhaps an option for users to swap out icons to another colour combo (with a few options) to provide the necessary contrast.

**Comment by johnnliu** [comment]
I love this one - thank you.

**Comment by johnnliu** [comment]
![image](https://user-images.githubusercontent.com/1279372/42513096-6f63192a-8499-11e8-8f45-67bdaefde4fd.png)

**Comment by johnnliu** [comment]
closing this task, but we may return in the future if we add an Options settings dialog.
