### ISSUE TITLE
current environment dropdown

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#71]
what is your favourite feature?

what is the nature of your bug emergency?

what would you like to see?
the currently selected environment should be visible

ask FlowNinja anything?

**Comment by johnnliu** [comment]
when screen width is below 990px and there is only 1 environment, the display for the current environment is hidden.

![image](https://user-images.githubusercontent.com/1279372/47080983-29321000-d255-11e8-9bb1-5c1409f775ea.png)

![image](https://user-images.githubusercontent.com/1279372/47080988-2fc08780-d255-11e8-8118-f5b924deb793.png)

When there are multiple environments - it isn't clear which one is currently selected.

![image](https://user-images.githubusercontent.com/1279372/47081002-3bac4980-d255-11e8-8f4f-2c219299fcb4.png)

**Comment by jakemannion** [comment]
I was juuuust about to add this (below) - did not realize that was a drop-down. Carry on!


![image](https://user-images.githubusercontent.com/41285392/49577142-a1cf5780-f8fb-11e8-9496-b86262367840.png)

**Comment by johnnliu** [comment]
![image](https://user-images.githubusercontent.com/1279372/64746036-71cd7880-d54d-11e9-94b6-8c2c9c5e49c2.png)

Slated for v0.2.16 
the current environment is now bold.
