### ISSUE TITLE
Import expressions created w/ the builder in Logic Apps

### ISSUE THREAD

**Issue by jakemannion** [johnnliu/Flow-Studio-Issues#79]
John, I thought [this article](https://sergeluca.wordpress.com/2018/03/23/new-conditional-builder-almost-available-in-microsoft-flow-i-guess/) was pretty interesting and wondered if you had seen it. Do you think FlowStudio could help integrate the builder in Logic Apps with the raw JSON in flow? 

If Flow is going to be receive a better expression builder, it's probably not worth it. Perhaps something's already been announced already? But if there are no plans, this could be fantastic.

**Comment by johnnliu** [comment]
the advanced condition editor will come to Flow soon I believe.  It's already in the UI, just not enabled.  
![image](https://user-images.githubusercontent.com/1279372/48002769-a0760800-e160-11e8-8b1d-aadc28787842.png)

because it's so close, I'm unlikely to build support for this into FlowStudio.

**Comment by jakemannion** [comment]
Okay cool, thanks John. Makes sense.
