### ISSUE TITLE
ChangeLog timestamp

### ISSUE THREAD

**Issue by johnnliu** [johnnliu/Flow-Studio-Issues#95]
hey John, just curious 
can you add timestamp to changelog?

**Comment by johnnliu** [comment]
all future ones or the past too?  I guess I can do a blame/annotate report on the change log component.

**Comment by jakemannion** [comment]
I'm sure you have bigger fish to fry, but future would be nice ...  past+ future would be even nicer. The thought process I had when I submitted the feedback was, "I love seeing the changelog, I just have a hard time telling _what's new_ since my last visit without reading the first couple entries"

**Comment by johnnliu** [comment]
well well 
![image](https://user-images.githubusercontent.com/1279372/54423458-d5284a80-4764-11e9-8f8c-471c92d78da8.png)

**Comment by johnnliu** [comment]
updated into the change log.

**Comment by jakemannion** [comment]
Thank youuuu @johnnliu
